export const accessMenuItems = [
  { to: '/dashboard', label: 'Dashboard' },
  { to: '/book-appointment', label: 'Book Appointment' },
  { to: '/appointments', label: 'Appointments' },
  { to: '/doctors', label: 'Doctors' },
  { to: '/receptionists', label: 'Receptionists' },
  { to: '/patients', label: 'Patients' },
  { to: '/admissions', label: 'Admissions' },
  { to: '/billing', label: 'Billing' },
  { to: '/reports', label: 'Reports' },
  { to: '/patient-reports', label: 'Patient Reports' },
  { to: '/doctor-reports', label: 'Doctor Reports' },
  { to: '/billing-reports', label: 'Billing Reports' },
  { to: '/appointment-reports', label: 'Appointment Reports' },
  { to: '/staff-reports', label: 'Staff Reports' },
  { to: '/staff', label: 'Staff' },
  { to: '/business-settings', label: 'Business Settings' },
  { to: '/about', label: 'About' },
  { to: '/contact', label: 'Contact' },
];
